### ISSUE TITLE
taxify "IndexError: list index out of range"

### ISSUE THREAD

**Issue by Jigyasa3** [DRL/blobtools#103]
Hey All

I am taxify-ing the blast output file against Uniprot database, following the tutorial here- https://blobtools.readme.io/docs/taxid-mapping-file.

The accessions file looks like this-
A4YCM6  NCBI_TaxID      399549
A4YCM7  NCBI_TaxID      399549
A4YCM8  NCBI_TaxID      399549
A4YCM9  NCBI_TaxID      399549
A4YCN0  NCBI_TaxID      399549
A4YCN1  NCBI_TaxID      399549
A4YCN2  NCBI_TaxID      399549

The blast output looks like this-
VOFB01000001.1  G4KY63  57.5    518     163     8       8389    6920    196     684     5.3e-140        510.0
VOFB01000002.1  R6I413  53.5    318     138     4       25221   24286   258     571     6.2e-85 327.4
VOFB01000003.1  R6NGL6  98.4    554     9       0       5612    3951    47      600     8.0e-307        1063.5
VOFB01000004.1  R6PNB2  98.4    127     2       0       1670    1290    197     323     1.3e-61 245.7

The code-
`blobtools taxify -f 2-uniprot-matches-VOFB01.fasta.out -m ${MAP_DIR}/uniprot_ref_proteomes.taxids -s 0 -t 2 -o VOFB01`

Error-
`[+] Parsing Mapping file - uniprot_ref_proteomes.taxids
Traceback (most recent call last):
  File "/bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/blobtools-blobtools_v1.1.1/blobtools", line 7, in <module>
    main()
  File "/bucket/.mabuya/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/blobtools-blobtools_v1.1.1/lib/interface.py", line 78, in main
    taxify.main()
  File "/bucket/.mabuya/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/blobtools-blobtools_v1.1.1/lib/taxify.py", line 79, in main
    taxid_d = BtIO.parseDict(map_f, map_col_sseqid, map_col_taxid)
  File "/bucket/.mabuya/BourguignonU/Jigs_backup/rotation_data/sasha_unit/virus-bacteria_interactions/scripts_softwares/blobtools-blobtools_v1.1.1/lib/BtIO.py", line 110, in parseDict
    items[temp[k_idx]] = temp[v_idx]
IndexError: list index out of range`

I am using python/3.7.3

**Comment by DRL** [comment]
Is the accession file a TSV?
