### ISSUE TITLE
Python issues

### ISSUE THREAD

**Issue by mw55309** [DRL/blobtools#43]
Hey

I'm using Python 3.4.  I get the error:

./blobtools/blobtools create --help
  File "./blobtools/bloblib/create.py", line 105
    print BtLog.warn_d['0']
              ^
SyntaxError: Missing parentheses in call to 'print'

Is this a Python 2 vs 3 issue?

Cheers
Mick

**Comment by DRL** [comment]
Hi Mick,

yes, unfortunately I haven't massaged the code to be Python3 compatible yet...

If you use Python2.7 all things should work.

cheers, 

dom

**Comment by mw55309** [comment]
Hmmm.  Not on eddie3:

ip install matplotlib
Collecting matplotlib
  Downloading matplotlib-2.0.0-1-cp27-cp27mu-manylinux1_x86_64.whl (14.6MB)
    100% |████████████████████████████████| 14.6MB 88kB/s
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.7.1 in /exports/eddie3_homes_local/mwatson9/.local/lib/python2.7/site-packages (from matplotlib)
Exception:
Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/mickpython/mypython2.7/lib/python2.7/email/feedparser.py", line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'


gah!

**Comment by DRL** [comment]
Interesting.

Are you using a virtualenv for installing the dependencies?

**Comment by mw55309** [comment]
I'm using conda as per the ECDF instructions: https://www.wiki.ed.ac.uk/display/ResearchServices/Anaconda

**Comment by DRL** [comment]
Oh, I did not know about this ...

you could do this though:

```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py --user
pip install --user virtualenv
mkdir virtualenvs
virtualenv virtualenvs/blobtools
source virtualenvs/blobtools/bin/activate
pip install matplotlib
pip install docopt
git clone https://github.com/DRL/blobtools.git
blobtools/blobtools -help
```
I have tested it and it works. For proper running you still need to download the NCBI taxdumps, though.

Since it is installed at the user level admins shouldn't be upset ...

cheers, 

dom
