### ISSUE TITLE
Python AttributeError AxesSubplot object has no attribute 'set_color'

### ISSUE THREAD

**Issue by AntoineHo** [DRL/blobtools#79]
Hello,
I have run into this issue after doing the following command:
`$ blobtools plot -i test.blobDB.json -o test.plot`
```
[+] Reading BlobDB test.blobDB.json
[+] 	Loading BlobDB into memory ...
[+] 	Deserialising BlobDB (using 'ujson' module) (this may take a while) ...
[+] 	Finished in 9.93609285355s
[+] Extracting data for plots ...
[I]	Chordata : sequences = 3,610, span = 58.84 MB, N50 = 42,376 nt
[I]	Arthropoda : sequences = 3,934, span = 50.75 MB, N50 = 35,510 nt
[I]	Proteobacteria : sequences = 3,100, span = 46.84 MB, N50 = 49,863 nt
[I]	Rotifera : sequences = 4,041, span = 30.44 MB, N50 = 20,021 nt
[I]	no-hit : sequences = 26,298, span = 26.97 MB, N50 = 1,527 nt
[I]	Mollusca : sequences = 1,253, span = 21.44 MB, N50 = 43,704 nt
[I]	Ascomycota : sequences = 677, span = 11.65 MB, N50 = 36,332 nt
[I]	other : sequences = 5,221, span = 58.34 MB, N50 = 30,949 nt
[+] Plotting test.plot.test.blobDB.json.bestsum.phylum.p7.span.100.blobplot.bam0.png
Traceback (most recent call last):
  File "/home/antoine/tools/blobtools/lib/blobplot.py", line 183, in <module>
    main()
  File "/home/antoine/tools/blobtools/lib/blobplot.py", line 179, in main
    plotObj.plotBar(cov_lib, out_f)
  File "/home/antoine/tools/blobtools/lib/BtPlot.py", line 546, in plotBar
    fig, ax_main, ax_group, x_pos_main, x_pos_group = self.setupPlot('readcov')
  File "/home/antoine/tools/blobtools/lib/BtPlot.py", line 525, in setupPlot
    ax_main.set_color(BGGREY)
AttributeError: 'AxesSubplot' object has no attribute 'set_color'
```

**Comment by DRL** [comment]
Most li

**Comment by DRL** [comment]
Most likely related to matplotlib version. New release should address this.

cheers, 

dom
