### ISSUE TITLE
taxify MemoryError

### ISSUE THREAD

**Issue by Yulia-Yakovleva** [DRL/blobtools#89]
Hi, I have an issue with **taxify** command.
**taxify -h** is ok, but when I want to generate HITS file, I see this:
**[+] Parsing Mapping file /db/nucl_wgs.accession2taxid
Traceback (most recent call last):
  File "/home/yulia/blobtools/lib/taxify.py", line 112, in <module>
    main()
  File "/home/yulia/blobtools/lib/taxify.py", line 83, in main
    taxid_d = BtIO.parseDict(map_f, map_col_sseqid, map_col_taxid)
  File "/home/yulia/miniconda3/lib/python2.7/site-packages/lib/BtIO.py", line 109, in parseDict
    items[temp[k_idx]] = temp[v_idx]
MemoryError**

I thougt, it could be a proplem with python 2 and 3 conflict, I've reinstalled all what is possible, but still have the same issue. It is okey with **help** calling, what can be wrong?
Thanks!

**Comment by DRL** [comment]
Not seen that before. Try using python3 and the latest release of blobtools
