### ISSUE TITLE
blobtools create: [ERROR:27]  nodesDB ("--db") could not be read

### ISSUE THREAD

**Issue by etvedte** [DRL/blobtools#95]
I ran blobtools create and it returned an error message stating nodes.dmp could not be read. Thinking this was related to the read only nature of the area of the filesystem where this was installed, I copied nodes.dmp to a different area and gave it read write and execute permissions. When I ran the following: 
blobtools create --db nodes.dmp -i reference.fasta -b sorted.bam -t blast.out -o my_first_blobplot

I saw the same error message: 
[ERROR:27]      : nodesDB ("--db") /local/projects-t3/RDBKO/dana.quickmerge/pb.sqII+minion.LIG.3X.polished/blobtools/nodes.dmp could not be read.

When I ran with --names and --nodes instead, I got this:

Traceback (most recent call last):
  File "/usr/local/packages/blobtools/blobtools", line 7, in <module>
    main()
  File "/usr/local/packages/blobtools-1.1/lib/interface.py", line 62, in main
    create.main()
  File "/usr/local/packages/blobtools-1.1/lib/create.py", line 103, in main
    nodesDB, nodesDB_f = BtIO.parseNodesDB(nodes=nodes_f, names=names_f, nodesDB=nodesDB_f, nodesDBdefault=nodesDB_default)
  File "/usr/local/packages/blobtools-1.1/lib/BtIO.py", line 619, in parseNodesDB
    writeNodesDB(nodesDB, nodesDB_f)
  File "/usr/local/packages/blobtools-1.1/lib/BtIO.py", line 660, in writeNodesDB
    with open(nodesDB_f, 'w') as fh:
OSError: [Errno 30] Read-only file system: '/usr/local/packages/blobtools-1.1/lib/../data/nodesDB.txt'

Any idea how I can resolve this issue?

**Comment by etvedte** [comment]
If blobtools is installed in a filesystem area that is read-only, the user can use the --names /path/to/names.dmp --nodes /path/to/nodes.dmp and --db /path/to/nodesDB.txt parameters together, with the nodesDB.txt file in an area that has write permissions.
